require_relative './src/api/purpur_api'
require_relative './src/api/spiget_api'
require_relative './src/services/config_generator_service'
require_relative './src/lib/hash_patch'
require_relative './src/lib/animations_service'