# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem "rspec", "~> 3.12"

gem "vcr", "~> 6.2"

gem "irb", "~> 1.7"

gem "rbs", "~> 3.1"

gem "steep", "~> 1.5"

gem "webmock", "~> 3.18"

gem "colored", "~> 1.2"

gem "dry-cli", "~> 1.0"
